/*
 * Constants.h
 *
 *  Created on: 13 Sep 2014
 *      Author: pdavies
 */

#ifndef CONSTANTS_H_
#define CONSTANTS_H_

//What's enabled
#define MAGNETOMETER 1
#define FLOW_SENSOR 1
#define PUMP_ON_FLOW 1
#define USE_PRESSURE 0
#define FLOAT_SWITCHES 1
#define ELSA_ALARM 0

#define OFF 0
#define ON 1

#define DEBOUNCE_NEEDED_ON_DIVERTER_BUTTON
//#define PUMP_ON_INPUT_FLOW 1
#define USE_OPTION_TYPE 1
#define DETAILED_LOGGING

#define FAN_OFFTIME 10

#define TICKS_PER_SECOND (1000/MILLIS_PER_TICK)

enum OPTIONS {
	OPT_SWITCHON_PRESSURE,
	OPT_EXTRACTOR_DWELL,
	OPT_SHOWER_LIGHTS_STAY,
	OPT_ALCOVE_LIGHTS_STAY,
	OPT_DANGER_PRESSURE_DIF,
	OPT_HUMIDITY_THRESHOLD,
	OPT_UNUSED1,
	OPT_DIVERTER_STATE,
	OPT_GLITZ_DELAY,
	OPT_POWER_ENABLE,
	OPT_DST_WRONG,
	OPT_PRESSURE_GAIN,
	OPT_FLOW_GAIN,
	OPT_HUMIDITY_CAL,
	OPT_COLD_TEMP,
	OPT_PURGE_DELAY,
	OPT_PURGE_TIME,
	OPT_STARTUP_VISUAL,
	OPT_FLOW_TRIP,
	OPT_FLOW_POWERPUMP_TRIP,
	OPT_MAGFIELD_GAIN,
	OPT_MAGFIELD_DANGER,
	OPT_MAGFIELD_TRIP,
	OPT_PUMP_LEAKY_BUCKET_LEAK_RATE,
	OPT_MAG_CAL_OFS,
	OPT_MAXTIME_FULL_DRAIN,
	OPT_MAXTIME_EXTRACTOR,
};

#define PULSES_PER_LITRE 45
#define MAX_SANE_PRESSURE_DIFFERENTIAL 500
//#define MAGFLD_OFS 50
#define MAX_FIELD_SWING 250

#define WATER_LEVEL_A_HIGH 1
#define WATER_LEVEL_B_HIGH 0
#define FLOAT_A_POWER_LEVEL 128
//#define FLOAT_B_POWER_LEVEL 230

#define MS_LONG_KEYPRESS 260
#define MS_SHORT_KEYPRESS 20

#define RL_ON 0
#define RL_OFF 1
#define OC_OFF 0
#define OC_ON 1
#define BUTTON_PRESSED 0
#define BUTTON_RELEASED 1
#define FLOAT_A_ACTIVATED 1
#define FLOAT_B_ACTIVATED 0
#define FLOAT_A_IDLE 0
#define FLOAT_B_IDLE 1


#define INITIAL_DISPLAY_MODE DisplayNS::NORMAL

#define DEBOUNCE_MILLIS 10

#define ARRAY_ELEMENTS(arr) (sizeof(arr)/sizeof(arr[0]))

#endif /* CONSTANTS_H_ */
